#!/bin/bash
dn=$(dirname $0)
source $dn/cert-utils.sh
file=$1

check_openssl

if __file_exist "$file" ; then
   result=$( _pem_extract "$file")
   _msg_info "extracted to $result "
else
    _msg_error " $file not found"
fi